@startuml StoryboarGenerator-DAO

class User{
    id
    name
    lastName
    email
    password
    phone
    age
    idetifier
    key
    ---
    login()
    register()
    recoverPassword()
    editProfile()
}

class TeamMember{
    id
    rol
    ---
    showProfile()
}

class Project{
    id
    producer
    startDate
    updateDate
    finishDate
    tittle
    description
    teamMembers
    scenes
    ---
    createProject()
    generateAccessPIN()
    editProject()
    manageMemberRol()
    deleteMember()
    notifyChanges()
    showLastUpdateDate()
    downloadPDF()
    deleteProject()
    accessProject()
    addScenes()
    deleteScenes()
    showAddedEscenes()
}
class Scene{
    id
    number
    duration
    place
    dayTime
    space
    planes
    ---
    createScene()
    editEscene()
    deleteEscene()
    showEscene()
    addPlanes()
    deletePlanes()
    showAddedPlanes()
}
class Plane{
    id
    number
    duration
    argument
    shot
    framing
    move
    ---
    createPlane()
    editPlane()
    showPlane()
    addImageFromCamera()
    addImageFromStorage()
}

User<|-left-TeamMember
TeamMember -up-o Project
Project*-right-Scene
Scene*-right-Plane

@enduml